services:
  cosmosdb:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:vnext-preview
    container_name: cosmosdb-emulator
    ports:
      - "8081:8081"
      - "1234:1234"
      - "10250-10255:10250-10255"
    environment:
      - AZURE_COSMOS_EMULATOR_PARTITION_COUNT=1
      - AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=false
    mem_limit: 4g
    cpus: 2.0

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite-emulator
    command: "azurite-blob --blobHost 0.0.0.0 --blobPort 10000"
    ports:
      - "10000:10000"
